// ─── Pastoral Options ──────────────────────────────────────
export const PASTORAIS = [
  "Acólitos",
  "Apostolado da Oração",
  "Balet",
  "Bazar Beneficente",
  "CAE",
  "Caminhando com Maria",
  "Canto Litúrgico",
  "Canto/Instrumento",
  "Catequese",
  "CEB Imaculada Conceição",
  "CEB Nossa Senhora das Graças",
  "CEB Nossa Senhora de Fátima",
  "CEB Nossa Senhora de Guadalupe",
  "CEB Nossa Senhora do Rocio",
  "CEB Sagrada Família",
  "CEB São José",
  "CNLB",
  "Confissões",
  "Coroinhas",
  "CPP",
  "Dízimo",
  "Diáconos",
  "GO - Nossa Senhora de Pentecostes",
  "Grupo de Reflexão (Capela)",
  "JDM",
  "Liturgia",
  "MECE",
  "Mãe Rainha",
  "Padre Valter",
  "PASCOM",
  "Pastoral da Criança",
  "Pastoral da Pessoa Idosa",
  "Pastoral Familiar",
  "Região Pastoral Nossa Senhora Aparecida",
  "Reserva de Batizados",
  "Reserva de Casamentos",
  "Secretaria",
  "Terço dos Homens",
  "Vicentinos",
] as const;

// ─── Tipo (Event Type) Options ─────────────────────────────
export const TIPOS = [
  "Assembleia",
  "Batizados",
  "Casamento",
  "Catequese",
  "Catequese Batismal",
  "Catequese Matrimonial",
  "Celebração da Palavra",
  "Conferência",
  "Confissões",
  "Confraternização",
  "Congresso",
  "Encontro",
  "Espiritualidade",
  "Evento",
  "Formação",
  "Missa",
  "Missa da Crisma",
  "Mutirão de Confissões",
  "Retiro",
  "Reunião",
  "Semana da Família",
  "Viagem",
  "Visitas e Casamentos (Pe Valter)",
  "Vivência com as Famílias",
] as const;

// ─── Local (Location) Options ──────────────────────────────
export const LOCAIS = [
  "Auditório Bom Pastor",
  "Capela - Nossa Senhora de Fátima",
  "Capela - Sala Carlo Acutis",
  "Capela - Sala Santa Helena",
  "Capela - Sala Três Pastorinhos",
  "Capela - Salão",
  "CEPA - Centro de Pastoral da Arquidiocese",
  "Chácara Bom Conselho em Marialva-PR",
  "Chácara Rainha da Paz",
  "Chácara Recanto Pascal",
  "Condomínio dos Idosos",
  "Matriz - Cozinha Salão",
  "Matriz - Igreja",
  "Matriz - Sacristia",
  "Matriz - Sala Santa Cecília",
  "Matriz - Sala Santa Rita de Cássia",
  "Matriz - Sala São João Paulo II",
  "Matriz - Sala São João XXIII",
  "Matriz - Salão",
  "Paróquia Santa Maria Goretti",
  "Sem Local Definido",
] as const;

// ─── Color Map for Tipos ───────────────────────────────────
// Modern color palette — each tipo gets a distinct hue
export const TIPO_COLORS: Record<string, { bg: string; text: string; border: string; dot: string }> = {
  "Assembleia":                        { bg: "bg-blue-50 dark:bg-blue-950/40",    text: "text-blue-700 dark:text-blue-300",    border: "border-blue-200 dark:border-blue-800",    dot: "bg-blue-500" },
  "Batizados":                         { bg: "bg-cyan-50 dark:bg-cyan-950/40",    text: "text-cyan-700 dark:text-cyan-300",    border: "border-cyan-200 dark:border-cyan-800",    dot: "bg-cyan-500" },
  "Casamento":                         { bg: "bg-pink-50 dark:bg-pink-950/40",    text: "text-pink-700 dark:text-pink-300",    border: "border-pink-200 dark:border-pink-800",    dot: "bg-pink-500" },
  "Catequese":                         { bg: "bg-green-50 dark:bg-green-950/40",  text: "text-green-700 dark:text-green-300",  border: "border-green-200 dark:border-green-800",  dot: "bg-green-500" },
  "Catequese Batismal":                { bg: "bg-emerald-50 dark:bg-emerald-950/40", text: "text-emerald-700 dark:text-emerald-300", border: "border-emerald-200 dark:border-emerald-800", dot: "bg-emerald-500" },
  "Catequese Matrimonial":             { bg: "bg-teal-50 dark:bg-teal-950/40",    text: "text-teal-700 dark:text-teal-300",    border: "border-teal-200 dark:border-teal-800",    dot: "bg-teal-500" },
  "Celebração da Palavra":             { bg: "bg-violet-50 dark:bg-violet-950/40", text: "text-violet-700 dark:text-violet-300", border: "border-violet-200 dark:border-violet-800", dot: "bg-violet-500" },
  "Conferência":                       { bg: "bg-indigo-50 dark:bg-indigo-950/40", text: "text-indigo-700 dark:text-indigo-300", border: "border-indigo-200 dark:border-indigo-800", dot: "bg-indigo-500" },
  "Confissões":                        { bg: "bg-purple-50 dark:bg-purple-950/40", text: "text-purple-700 dark:text-purple-300", border: "border-purple-200 dark:border-purple-800", dot: "bg-purple-500" },
  "Confraternização":                  { bg: "bg-amber-50 dark:bg-amber-950/40",  text: "text-amber-700 dark:text-amber-300",  border: "border-amber-200 dark:border-amber-800",  dot: "bg-amber-500" },
  "Congresso":                         { bg: "bg-sky-50 dark:bg-sky-950/40",      text: "text-sky-700 dark:text-sky-300",      border: "border-sky-200 dark:border-sky-800",      dot: "bg-sky-500" },
  "Encontro":                          { bg: "bg-orange-50 dark:bg-orange-950/40", text: "text-orange-700 dark:text-orange-300", border: "border-orange-200 dark:border-orange-800", dot: "bg-orange-500" },
  "Espiritualidade":                   { bg: "bg-fuchsia-50 dark:bg-fuchsia-950/40", text: "text-fuchsia-700 dark:text-fuchsia-300", border: "border-fuchsia-200 dark:border-fuchsia-800", dot: "bg-fuchsia-500" },
  "Evento":                            { bg: "bg-rose-50 dark:bg-rose-950/40",    text: "text-rose-700 dark:text-rose-300",    border: "border-rose-200 dark:border-rose-800",    dot: "bg-rose-500" },
  "Formação":                          { bg: "bg-lime-50 dark:bg-lime-950/40",    text: "text-lime-700 dark:text-lime-300",    border: "border-lime-200 dark:border-lime-800",    dot: "bg-lime-500" },
  "Missa":                             { bg: "bg-yellow-50 dark:bg-yellow-950/40", text: "text-yellow-700 dark:text-yellow-300", border: "border-yellow-200 dark:border-yellow-800", dot: "bg-yellow-500" },
  "Missa da Crisma":                   { bg: "bg-gold/10 dark:bg-gold/20",        text: "text-gold-dark dark:text-gold-light", border: "border-gold/30 dark:border-gold/40",      dot: "bg-gold" },
  "Mutirão de Confissões":             { bg: "bg-purple-50 dark:bg-purple-950/40", text: "text-purple-700 dark:text-purple-300", border: "border-purple-200 dark:border-purple-800", dot: "bg-purple-400" },
  "Retiro":                            { bg: "bg-slate-50 dark:bg-slate-950/40",  text: "text-slate-700 dark:text-slate-300",  border: "border-slate-200 dark:border-slate-800",  dot: "bg-slate-500" },
  "Reunião":                           { bg: "bg-zinc-50 dark:bg-zinc-950/40",    text: "text-zinc-700 dark:text-zinc-300",    border: "border-zinc-200 dark:border-zinc-800",    dot: "bg-zinc-500" },
  "Semana da Família":                 { bg: "bg-red-50 dark:bg-red-950/40",      text: "text-red-700 dark:text-red-300",      border: "border-red-200 dark:border-red-800",      dot: "bg-red-500" },
  "Viagem":                            { bg: "bg-sky-50 dark:bg-sky-950/40",      text: "text-sky-700 dark:text-sky-300",      border: "border-sky-200 dark:border-sky-800",      dot: "bg-sky-400" },
  "Visitas e Casamentos (Pe Valter)":  { bg: "bg-pink-50 dark:bg-pink-950/40",    text: "text-pink-700 dark:text-pink-300",    border: "border-pink-200 dark:border-pink-800",    dot: "bg-pink-400" },
  "Vivência com as Famílias":          { bg: "bg-rose-50 dark:bg-rose-950/40",    text: "text-rose-700 dark:text-rose-300",    border: "border-rose-200 dark:border-rose-800",    dot: "bg-rose-400" },
};

const DEFAULT_COLOR = { bg: "bg-gray-50 dark:bg-gray-950/40", text: "text-gray-700 dark:text-gray-300", border: "border-gray-200 dark:border-gray-800", dot: "bg-gray-500" };

export function getTipoColor(tipo: string) {
  return TIPO_COLORS[tipo] ?? DEFAULT_COLOR;
}
