import { PrismaClient } from "@prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import bcrypt from "bcryptjs";

const adapter = new PrismaLibSql({
  url: process.env.DATABASE_URL || "file:./dev.db",
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const prisma = new PrismaClient({ adapter });

async function main() {
  const passwordHash = await bcrypt.hash("admin123", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@paroquia.com" },
    update: {},
    create: {
      name: "Administrador",
      email: "admin@paroquia.com",
      passwordHash,
      role: "admin",
      isActive: true,
    },
  });

  console.log("Admin user created:", admin.email);

  // Clear existing events before re-seeding
  await prisma.event.deleteMany({});

  const events = [
    // ── March 2026 ──────────────────────────────────────────────
    {
      title: "Missa do Jubileu — 25 Anos",
      date: "2026-03-01",
      description: "Celebração especial pelos 25 anos da Paróquia Nossa Senhora Aparecida com missa solene e procissão.",
      startTime: "10:00",
      endTime: "12:00",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Reunião do Apostolado da Oração",
      date: "2026-03-02",
      description: "Encontro mensal do grupo para organização das atividades e orações comunitárias.",
      startTime: "19:00",
      endTime: "20:30",
      pastoral: "Apostolado da Oração",
      tipo: "Reunião",
      local: "Matriz - Sala Santa Cecília",
      createdById: admin.id,
    },
    {
      title: "Catequese Infantil — Turma A",
      date: "2026-03-04",
      description: "Aula de catequese para crianças de 8 a 10 anos, preparação para Primeira Eucaristia.",
      startTime: "09:00",
      endTime: "10:30",
      pastoral: "Catequese",
      tipo: "Catequese",
      local: "Matriz - Sala São João XXIII",
      createdById: admin.id,
    },
    {
      title: "Confissões — Quaresma",
      date: "2026-03-04",
      description: "Confissões abertas à comunidade durante o período quaresmal.",
      startTime: "16:00",
      endTime: "19:00",
      pastoral: "Confissões",
      tipo: "Confissões",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Encontro de Jovens — JDM",
      date: "2026-03-06",
      description: "Encontro semanal da Juventude Diocesana Mariana com dinâmicas, oração e partilha.",
      startTime: "19:30",
      endTime: "21:30",
      pastoral: "JDM",
      tipo: "Encontro",
      local: "Matriz - Salão",
      createdById: admin.id,
    },
    {
      title: "Assembleia Paroquial",
      date: "2026-03-07",
      description: "Assembleia geral com todas as pastorais para planejamento do primeiro semestre.",
      startTime: "09:00",
      endTime: "12:00",
      pastoral: "CPP",
      tipo: "Assembleia",
      local: "Auditório Bom Pastor",
      createdById: admin.id,
    },
    {
      title: "Missa dos Enfermos",
      date: "2026-03-08",
      description: "Missa especial com unção dos enfermos e bênção dos doentes.",
      startTime: "10:00",
      endTime: "11:30",
      pastoral: "Pastoral da Pessoa Idosa",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Terço dos Homens",
      date: "2026-03-09",
      description: "Encontro mensal do grupo Terço dos Homens com terço, cânticos e partilha.",
      startTime: "19:00",
      endTime: "20:30",
      pastoral: "Terço dos Homens",
      tipo: "Encontro",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Catequese Batismal",
      date: "2026-03-11",
      description: "Encontro de catequese para pais e padrinhos de crianças que serão batizadas.",
      startTime: "19:30",
      endTime: "21:00",
      pastoral: "Catequese",
      tipo: "Catequese Batismal",
      local: "Matriz - Sala São João Paulo II",
      createdById: admin.id,
    },
    {
      title: "Retiro Quaresmal — Adultos",
      date: "2026-03-13",
      description: "Retiro espiritual de fim de semana para adultos com palestras, orações e confissões.",
      startTime: "08:00",
      endTime: "18:00",
      pastoral: "GO - Nossa Senhora de Pentecostes",
      tipo: "Retiro",
      local: "Chácara Rainha da Paz",
      createdById: admin.id,
    },
    {
      title: "Retiro Quaresmal — Adultos (Dia 2)",
      date: "2026-03-14",
      description: "Segundo dia do retiro espiritual quaresmal com encerramento e missa.",
      startTime: "08:00",
      endTime: "17:00",
      pastoral: "GO - Nossa Senhora de Pentecostes",
      tipo: "Retiro",
      local: "Chácara Rainha da Paz",
      createdById: admin.id,
    },
    {
      title: "Missa do Jubileu de Prata",
      date: "2026-03-15",
      description: "Missa solene pelos 25 anos da paróquia com participação dos grupos e pastorais.",
      startTime: "10:00",
      endTime: "12:00",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Batizados — Turma de Março",
      date: "2026-03-15",
      description: "Celebração do sacramento do Batismo para 12 crianças da comunidade.",
      startTime: "14:00",
      endTime: "15:30",
      pastoral: "Reserva de Batizados",
      tipo: "Batizados",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Formação para Acólitos",
      date: "2026-03-16",
      description: "Encontro de formação e treinamento para os acólitos da paróquia.",
      startTime: "14:00",
      endTime: "16:00",
      pastoral: "Acólitos",
      tipo: "Formação",
      local: "Matriz - Sala Santa Rita de Cássia",
      createdById: admin.id,
    },
    {
      title: "Reunião PASCOM",
      date: "2026-03-17",
      description: "Reunião da Pastoral da Comunicação para planejamento das redes sociais e comunicados.",
      startTime: "19:00",
      endTime: "20:30",
      pastoral: "PASCOM",
      tipo: "Reunião",
      local: "Matriz - Sala Santa Cecília",
      createdById: admin.id,
    },
    {
      title: "Catequese — Crisma Jovens",
      date: "2026-03-18",
      description: "Aula de catequese para jovens em preparação para o sacramento da Crisma.",
      startTime: "19:00",
      endTime: "20:30",
      pastoral: "Catequese",
      tipo: "Catequese",
      local: "Matriz - Sala São João Paulo II",
      createdById: admin.id,
    },
    {
      title: "Confissões Comunitárias",
      date: "2026-03-18",
      description: "Celebração penitencial comunitária com vários confessores disponíveis.",
      startTime: "19:30",
      endTime: "21:30",
      pastoral: "Confissões",
      tipo: "Mutirão de Confissões",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Encontro de Casais — Pastoral Familiar",
      date: "2026-03-21",
      description: "Encontro de formação para casais com reflexão sobre vida familiar e fé.",
      startTime: "19:30",
      endTime: "21:30",
      pastoral: "Pastoral Familiar",
      tipo: "Encontro",
      local: "Auditório Bom Pastor",
      createdById: admin.id,
    },
    {
      title: "Viagem — Congresso Arquidiocesano",
      date: "2026-03-22",
      description: "Viagem dos representantes paroquiais ao Congresso Arquidiocesano em Maringá.",
      startTime: "07:00",
      endTime: "18:00",
      pastoral: "Região Pastoral Nossa Senhora Aparecida",
      tipo: "Viagem",
      local: "CEPA - Centro de Pastoral da Arquidiocese",
      createdById: admin.id,
    },
    {
      title: "Casamento — Família Oliveira & Santos",
      date: "2026-03-22",
      description: "Celebração do sacramento do matrimônio.",
      startTime: "16:00",
      endTime: "17:30",
      pastoral: "Reserva de Casamentos",
      tipo: "Casamento",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Missa da Crisma",
      date: "2026-03-25",
      description: "Celebração do sacramento da Crisma para os jovens da paróquia. Presidida pelo Arcebispo.",
      startTime: "19:00",
      endTime: "21:00",
      pastoral: "Catequese",
      tipo: "Missa da Crisma",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Reunião CEB — Sagrada Família",
      date: "2026-03-25",
      description: "Encontro mensal da Comunidade Eclesial de Base Sagrada Família.",
      startTime: "19:00",
      endTime: "20:30",
      pastoral: "CEB Sagrada Família",
      tipo: "Reunião",
      local: "Matriz - Sala São João XXIII",
      createdById: admin.id,
    },
    {
      title: "Conferência — Espiritualidade Mariana",
      date: "2026-03-27",
      description: "Conferência sobre a espiritualidade mariana com palestrante convidado.",
      startTime: "19:30",
      endTime: "21:30",
      pastoral: "Caminhando com Maria",
      tipo: "Conferência",
      local: "Auditório Bom Pastor",
      createdById: admin.id,
    },
    {
      title: "Bazar Beneficente — Preparação",
      date: "2026-03-28",
      description: "Organização e preparação dos itens para o bazar beneficente de abril.",
      startTime: "08:00",
      endTime: "12:00",
      pastoral: "Bazar Beneficente",
      tipo: "Reunião",
      local: "Matriz - Cozinha Salão",
      createdById: admin.id,
    },
    {
      title: "Missa de Ramos — Domingo de Páscoa",
      date: "2026-03-29",
      description: "Missa do Domingo de Ramos com bênção dos ramos e procissão.",
      startTime: "09:00",
      endTime: "11:00",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Celebração da Palavra — CEB Fátima",
      date: "2026-03-30",
      description: "Celebração da Palavra da CEB Nossa Senhora de Fátima.",
      startTime: "19:00",
      endTime: "20:00",
      pastoral: "CEB Nossa Senhora de Fátima",
      tipo: "Celebração da Palavra",
      local: "Capela - Sala Três Pastorinhos",
      createdById: admin.id,
    },
    // ── February 2026 ────────────────────────────────────────────
    {
      title: "Missa de Carnaval",
      date: "2026-02-17",
      description: "Missa especial durante o feriado de carnaval para quem permanece na cidade.",
      startTime: "09:00",
      endTime: "10:30",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Formação de Catequistas",
      date: "2026-02-21",
      description: "Encontro de formação continuada para os catequistas da paróquia.",
      startTime: "09:00",
      endTime: "12:00",
      pastoral: "Catequese",
      tipo: "Formação",
      local: "Auditório Bom Pastor",
      createdById: admin.id,
    },
    {
      title: "Quarta-feira de Cinzas",
      date: "2026-02-18",
      description: "Celebração da Quarta-feira de Cinzas com imposição das cinzas e início da Quaresma.",
      startTime: "07:00",
      endTime: "08:00",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    // ── April 2026 ───────────────────────────────────────────────
    {
      title: "Vigília Pascal",
      date: "2026-04-04",
      description: "Vigília Pascal — a maior celebração do ano litúrgico com acendimento do fogo novo.",
      startTime: "21:00",
      endTime: "23:30",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Missa de Páscoa",
      date: "2026-04-05",
      description: "Missa solene de Páscoa com canto do Aleluia e celebração da Ressurreição.",
      startTime: "10:00",
      endTime: "12:00",
      pastoral: "Liturgia",
      tipo: "Missa",
      local: "Matriz - Igreja",
      createdById: admin.id,
    },
    {
      title: "Catequese — Início das Aulas",
      date: "2026-04-08",
      description: "Início do ano catequético para crianças e jovens da comunidade paroquial.",
      startTime: "09:00",
      endTime: "11:00",
      pastoral: "Catequese",
      tipo: "Catequese",
      local: "Matriz - Sala São João XXIII",
      createdById: admin.id,
    },
    {
      title: "Bazar Beneficente",
      date: "2026-04-18",
      description: "Bazar beneficente anual com produtos doados pela comunidade. Renda para obras sociais.",
      startTime: "09:00",
      endTime: "17:00",
      pastoral: "Bazar Beneficente",
      tipo: "Evento",
      local: "Matriz - Salão",
      createdById: admin.id,
    },
    {
      title: "Semana da Família",
      date: "2026-04-26",
      description: "Semana dedicada às famílias com atividades, missa especial e confraternização.",
      startTime: "09:00",
      endTime: "12:00",
      pastoral: "Pastoral Familiar",
      tipo: "Semana da Família",
      local: "Auditório Bom Pastor",
      createdById: admin.id,
    },
  ];

  await prisma.event.createMany({ data: events });

  console.log(`${events.length} events created.`);

  const banners = [
    {
      title: "Show de Louvor 2026",
      subtitle: "Uma noite especial de adoração",
      description:
        "Venha celebrar com a comunidade em uma noite de louvor, adoração e música. Traga sua família e amigos para este momento único de encontro com Deus.",
      date: "2026-04-18",
      startTime: "19:30",
      endTime: "22:00",
      location: "Paróquia Nossa Sra. Aparecida",
      ctaText: "Saiba Mais",
      ctaUrl: "#contato",
      gradient: "from-[#4a1942] via-navy to-royal",
      order: 0,
      createdById: admin.id,
    },
    {
      title: "Festa do Jubileu — 25 Anos",
      subtitle: "Celebração especial",
      description:
        "Celebramos 25 anos de fé e comunidade com uma programação especial: missa solene, almoço comunitário e apresentações culturais.",
      date: "2026-05-10",
      startTime: "09:00",
      endTime: "17:00",
      location: "Salão Paroquial",
      ctaText: "Participar",
      ctaUrl: "#contato",
      gradient: "from-gold-dark via-gold to-gold-light",
      order: 1,
      createdById: admin.id,
    },
    {
      title: "Retiro de Quaresma",
      subtitle: "Espiritualidade e reflexão",
      description:
        "Um fim de semana de retiro espiritual para jovens e adultos. Palestras, dinâmicas e momentos de oração em ambiente acolhedor.",
      date: "2026-03-13",
      startTime: "08:00",
      endTime: "18:00",
      location: "Chácara Rainha da Paz",
      gradient: "from-navy via-royal to-sky",
      order: 2,
      createdById: admin.id,
    },
  ];

  await prisma.banner.deleteMany({});
  await prisma.banner.createMany({ data: banners });

  console.log(`${banners.length} banners created.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
